---
name: Code review using Rubocop
author: Money Forward, Inc.
description: Analyze code statically using Rubocop in Github actions
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'orange'
